# Generated by Django 3.0.6 on 2020-05-28 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de modificación')),
                ('version', models.IntegerField(default=1, verbose_name='Versión')),
                ('cuit', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tipo_titular', models.CharField(blank=True, max_length=8, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('apellido', models.CharField(blank=True, max_length=250, null=True)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('año_fundacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Titular',
                'verbose_name_plural': 'Titulares',
            },
        ),
    ]
