# Generated by Django 3.0.6 on 2020-05-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulares',
            name='año_fundacion',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='titulares',
            name='cuit',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='titulares',
            name='tipo_titular',
            field=models.CharField(max_length=8),
        ),
    ]
