# Generated by Django 3.0.6 on 2020-05-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0002_auto_20200529_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulares',
            name='año_fundacion',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año de fundacion'),
        ),
        migrations.AlterField(
            model_name='titulares',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razon social'),
        ),
        migrations.AlterField(
            model_name='titulares',
            name='tipo_titular',
            field=models.CharField(max_length=8, verbose_name='Tipo de titular'),
        ),
    ]
