# Generated by Django 3.0.6 on 2020-06-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0003_auto_20200529_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulares',
            name='año_fundacion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fundacion'),
        ),
    ]
