# Generated by Django 3.0.6 on 2020-06-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0004_auto_20200531_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulares',
            name='año_fundacion',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año de fundacion'),
        ),
    ]
